### ISSUE TITLE
Consider using reduction form of test files and names to make it possible to display plugin controls on shrinked window

### ISSUE THREAD

**Issue by KvanTTT** [demiurg906/test-data-helper-plugin#30]
Normally I have the following window:

![image](https://github.com/demiurg906/test-data-helper-plugin/assets/1150330/3cadbe17-6703-43c5-927a-e72f4931558d)

But if I shink it a little bit I get the following (no controls except for arrow buttons):

![image](https://github.com/demiurg906/test-data-helper-plugin/assets/1150330/03d71405-2fc7-479a-9c2a-25f96f868e4a)

It's a bit annoying because I want my window to be minimal with controls. It's especially actual when file names are quite long.

I suggest hiding controls not when full name doesn't fit combo box width but when combo box's width less than minimal. It's possible to use `...` at the end of name to make it fitable into combo box.

**Comment by demiurg906** [comment]
I actually have no idea how this hiding works (it's some builtin IDEA functionality), and it also annoys me sometimes
